# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c65666778e9dbfab833a052427ad8486cd6cfe5849203288f9050947f4fd6c57a40341659f47e091d36d0e61b4c1cef22dc410827fadb9d699a5aebe83a0c7ba

test:
  secret_key_base: c5511c1b95620ef459c20d37a047b73088e8f9a0249b56951dc4dcf4e58cc68db29a296c8eaa7632709e607f6362da2b8f8eadcf4c0bf0cb7e291ca0aca4f3ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
