export const PREDICT_OUTFIT_SUCCESS = "PREDICT_OUTFIT_SUCCESS";
export const PREDICT_OUTFIT_FAIL = "PREDICT_OUTFIT_FAIL";

export const FETCH_COLORS_SUCCESS = "FETCH_COLORS_SUCCESS";
export const FETCH_COLORS_FAIL = "FETCH_COLORS_FAIL";


export const CREATE_COLOR_SUCCESS = "CREATE_COLOR_SUCCESS";
export const CREATE_COLOR_FAIL = "CREATE_COLOR_FAIL";

export const FETCH_OUTFITS_SUCCESS = "FETCH_OUTFITS_SUCCESS";
export const FETCH_OUTFITS_FAIL = "FETCH_OUTFITS_FAIL";

export const CREATE_OUTFITS_SUCCESS = "CREATE_OUTFITS_SUCCESS";
export const CREATE_OUTFITS_FAIL = "CREATE_OUTFITS_FAIL";

export const FETCH_SHIRTS_SUCCESS = "FETCH_SHIRTS_SUCCESS";
export const FETCH_SHIRTS_FAIL = "FETCH_SHIRTS_FAIL";

export const FETCH_PANTS_SUCCESS = "FETCH_PANTS_SUCCESS";
export const FETCH_PANTS_FAIL = "FETCH_PANTS_FAIL";


export const CREATE_SHIRT_SUCCESS = "CREATE_SHIRT_SUCCESS";
export const CREATE_SHIRT_FAIL = "CREATE_SHIRT_FAIL";

export const CREATE_PANTS_SUCCESS = "CREATE_PANTS_SUCCESS";
export const CREATE_PANTS_FAIL = "CREATE_PANTS_FAIL";

export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_FAIL = "AUTHENTICATE_FAIL";
