export const PREDICT_OUTFIT_SUCCESS = "PREDICT_OUTFIT_SUCCESS";
export const PREDICT_OUTFIT_FAIL = "PREDICT_OUTFIT_FAIL";

export const FETCH_COLORS_SUCCESS = "FETCH_COLORS_SUCCESS";
export const FETCH_COLORS_FAIL = "FETCH_COLORS_FAIL";
